### PR TITLE
Compatibility with Dart 2.1.1

### PR DESCRIPTION
**Pull request by bashenk**
Updated the gradle plugin, a few dependencies, modified compile target to android 28, fixed a typo, and resolved the new API issues with protobuf and dart:convert.

Possibly check over lib\generated\bledata.pb.dart, as it was hastily done.

### CODE REVIEW

**Comment by noordawod** [comment]
@PabloPL 

Is this library alive? Do you need help in maintaining it? Would like to help out as my company is going to invest time and resources in BLE for Flutter. Let me know.

Co-maintaining this: github.com/long1eu/flutter_i18n

**Comment by PabloPL** [comment]
@noordawod 
This plugin was created by Polidea, i wasn't maintaining it.
It looks like it was not maintained for while but they will bring it (at some time).
For me it was working fine (and better than other libraries which i've tried).

**Comment by noordawod** [comment]
Thanks @PabloPL. I thought you were maintaining it.

Well, how about it guys: @dariuszseweryn @paweljaneczek @uKL @bartoszstelmaszuk @Axadiw?

**Comment by pawelByszewski** [comment]
@bashenk @PabloPL @noordawod It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November.

**Comment by noordawod** [comment]
Wow, great news! Link?

**Comment by pawelByszewski** [comment]
@noordawod We merged the new version with updated readme into the master yesterday. Snapshot version of 2.0.0 is available on pub.dev https://pub.dev/packages/flutter_ble_lib/versions/2.0.0-dev.4

**Comment by pawelByszewski** [comment]
@noordawod have you had a chance to check out the lib? is there any missing feature from your perspective?

**Comment by noordawod** [comment]
@pawelByszewski I checked it, yeah, but not as extensively as I wanted to. I would say that it's well thought of and complete for my use case, but your mileage may vary.

**Pull request closed without merging**
